## Import Numpy

In [ ]:
import numpy as np #Aliasing - faster than having to type 'numpy' everytime

## Creating an Array

In [ ]:
a = np.array([1,2,3])
b = np.array([ [1,2,3], [4,5,6] ])
c = np.array([ [1,3,5,7], [2,4,6,8] ])
print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 3 5 7]
 [2 4 6 8]]


## Creating an Array with a specified DataType

In [ ]:
d = np.array([2,3,5,7,9])
print(d.dtype)

#int32 => 32 bits is the size of each element i.e. 4 bytes.

f_array = np.array([2,4,6,7,8], dtype = 'float16') 
print(f_array.dtype)

##to change  datatype, use: f_array.astype(np.int32)

int64
float16


##  (I) Basics

#### 1. Dimensions

In [ ]:
dim_a = a.ndim
dim_b = b.ndim
print(dim_a)
print(dim_b)

1
2


#### Exercise 1.1

In [ ]:
#Get the dimensions of c:
dim_c = c.ndim
print(dim_c)


2


#### 2. Shape

In [ ]:
shape_a = a.shape
shape_b = b.shape
print(shape_a)
print(shape_b)


(3,)
(2, 3)


#### Exercise 1.2

In [ ]:
#Get shape of C
print(c.shape)

(2, 4)


#### 3. Item size

In [ ]:

#It returns the size of each element of the array in BYTES. Since we're using int32, that means 
#we have 32 bits, So to convert from bits to bytes, just divide by 8. 32/8=4.
#Hence, we'll get 4 bytes as the answer every time.

size_a = a.itemsize
print(size_a)

print(b.itemsize)

8
8


#### 4. Size

In [ ]:
#It basically counts the number of elements in all the arrays in the given array. 

print(a.size)
size_b = b.size
print(size_b)
#print(c.size)

3
6


#### 5. Total Size

In [ ]:

#It basically gives us the size of the array, but in bytes.
#i.e. the summation of itemsizes of all elements. 
#i.e. (a.size)*(a.itemsize)
#Analogy: Suppose you have 4 items (length function) and each item weighs 1kg (itemsize).
#How much is the total weight of the bag?
#So what do you think is the total size of a and b?


In [ ]:
tsize_a = a.nbytes
print(tsize_a)

print(b.nbytes)
print(c.nbytes)

24
48
64


## (II) Accessing elements, sequence of elements, rows and columns

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#### 1. Accessing a specific element 

#### Exercise 2.1

In [ ]:
#Access 8 in a:
print(a[1,2])
#Access 11 
print(a[2,0])
#Access 19
print(a[-2,-2])

8
11
19


#### 2. Accessing an entire row:

In [ ]:
#To access the second row of a, do:
second_row = a[1,:]
print(second_row)

[ 6  7  8  9 10]


#### Exercise 2.2

In [ ]:
#access last row:
print(a[-1,:])

[21 22 23 24 25]


#### 3. Accessing an entire column:

In [ ]:
#To access the first column:
first_column = a[:,0]
print(first_column)

last_column = a[:,-1]
print(last_column)

[ 1  6 11 16 21]
[ 5 10 15 20 25]


#### Exercise 2.3

In [ ]:
#access 4th column:
print(a[:,-2])
#access 2nd column:
print(a[:,1])

[ 4  9 14 19 24]
[ 2  7 12 17 22]


#### 4. Accessing a sequence of elements and displaying them as a single array:
#### SEQUENCE INDEXING

In [ ]:
#syntax: a[start index : end index : step]
#For example, suppose we have to access elements from 10 to 12. Then do:
array1 = a[2,1:4:1]
print(array1)

#Second example: access elements 13 and 15

[12 13 14]


#### Exercise 2.4

In [ ]:
#Block accessing 1 - step = 1
#Access 11,12,16,17
print(a[2:4:1,0:2:1])

#Block accessing 2 - step = 1
#Access 8,9,10,13,14,15,18,19,20
print(a[1:4:1,2:5:1])

#Block accessing 3 - step = 2
#Access 1,3,5,11,13,15,21,23,25
print(a[0:5:2,0:5:2])

#Diagonal accessing
#Access 2,8,14,20
print(a[[0,1,2,3],[1,2,3,4]])

#Random Accessing
#Access 4,5,14,15,19,20
print(a[[0,2,3],3:5:1])

[[11 12]
 [16 17]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
[ 2  8 14 20]
[[ 4  5]
 [14 15]
 [19 20]]


In [ ]:
x = a[[4,3,2,1,0],[0,1,2,3,4]]
y = a[0:5:1,0:3:1]
z = a[[0,1,3,4],0:2:1]
w = a[0:4:1,0:2:1]
print(a[[0,1,3,4],0:3:1])

[[ 1  2  3]
 [ 6  7  8]
 [16 17 18]
 [21 22 23]]


## (III) Changing Elements 

#### 1. Changing elements:

In [ ]:
#Now that we've learnt how to access a particular element, it's quite simple to change 
#that accessed element(s).
#For example, if we want to change 10 to 100, we access 10 and change it to 100 by :
a[1,4] = 100
print(a)


[[  1   2   3   4   5]
 [  6   7   8   9 100]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]


#### Exercise 3.1

In [ ]:
#Change 20 to 200
a[3,4]=200
print(a)

[[  1   2   3   4   5]
 [  6   7   8   9 100]
 [ 11  12  13  14  15]
 [ 16  17  18  19 200]
 [ 21  22  23  24  25]]


#### 2. Changing an entire row

In [ ]:
#make it so that all the elements in the last row are 50
a[4,:]=50
print(a)

[[  1   2   3   4   5]
 [  6   7   8   9 100]
 [ 11  12  13  14  15]
 [ 16  17  18  19 200]
 [ 50  50  50  50  50]]


#### Exercise 3.2 

In [ ]:
#Change all the elements of the third row to 72
a[2,:]=72
print(a)

[[  1   2   3   4   5]
 [  6   7   8   9 100]
 [ 72  72  72  72  72]
 [ 16  17  18  19 200]
 [ 50  50  50  50  50]]


#### 3. Changing an entire column

In [ ]:
#make it so that all the elements of the last column are 80 
a[:,4]=80
print(a)

[[ 1  2  3  4 80]
 [ 6  7  8  9 80]
 [72 72 72 72 80]
 [16 17 18 19 80]
 [50 50 50 50 80]]


#### Exercise 3.3

In [ ]:
#Make it so that all the elements in the second column are 77
a[:,1]=77
print(a)

[[ 1 77  3  4 80]
 [ 6 77  8  9 80]
 [72 77 72 72 80]
 [16 77 18 19 80]
 [50 77 50 50 80]]


#### 4. Changing a row/column to specified elements

In [ ]:
a[0,:]=10,20,30,40,50
print(a)

[[10 20 30 40 50]
 [ 6 77  8  9 80]
 [72 77 72 72 80]
 [16 77 18 19 80]
 [50 77 50 50 80]]


#### Exercise 3.4

In [ ]:
#Using column replacements, change the last column to elements 100,200,300,400,500
a[:,4] = [100,200,300,400,500]
print(a)

[[ 10  20  30  40 100]
 [  6  77   8   9 200]
 [ 72  77  72  72 300]
 [ 16  77  18  19 400]
 [ 50  77  50  50 500]]


## (IV) Intitializing (creating) different types of arrays

#### 1. All 0s and all 1s matrix

In [ ]:
#This will create a matrix of given shape such that all elements in it are zeroes
matrix1 = np.zeros((3,4))
print(matrix1)

matrix2 = np.ones((4,3))
print(matrix2)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### Exercise 4.1 

In [ ]:
#Create an all zeroes matrix with 9 columns and 3 rows
print(np.zeros((3,9)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 2. All Ns matrix

In [ ]:
#create a matrix with a given number N of shape mxn
matrix3 = np.full((3,4),96)
print(matrix3)

[[96 96 96 96]
 [96 96 96 96]
 [96 96 96 96]]


#### 3. Full Like Matrices

In [ ]:
matrix3 = np.full_like(a,7)
print(matrix3)


[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


#### 4. Random integer matrices 

In [ ]:
matrix4 = np.random.randint(10,size=(4,4))
print(matrix4)
#note that 10 is excluded

#creating a matrix with random integers from 11 to 20
matrix5 = np.random.randint(11,21, size =(3,3))
print(matrix5)
#note that 11 is included, 21 is excluded

[[8 4 6 2]
 [6 0 3 3]
 [0 5 8 2]
 [4 7 8 0]]
[[18 12 13]
 [17 11 15]
 [20 16 20]]


#### 5. Random floating point value matrices

In [ ]:
matrix6 = np.random.rand(2,2)
print(matrix6)

[[0.39610428 0.11582602]
 [0.2163865  0.04140409]]


#### 6. Identity Matrices


In [ ]:
matrix7 = np.identity(3)
print(matrix7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## (V) Mathematical Operations on Matrices

#### 1. Addition, Subtraction

In [ ]:
#One of the advantages of using numpy is that we can straightaway add numbers to an entire array
#for example:
matrix8 = np.array([[1,2,3],[4,5,6]])
matrix9 = matrix8 + 1
print(matrix9)

[[2 3 4]
 [5 6 7]]


#### 2. Multiplication, Division

In [ ]:
matrix10 = np.array([10,20,30,40,50,60,70,80,90,100])
matrix11 = matrix10/10
print(matrix11)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
matrix12 = matrix11 * 10
print(matrix12)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
matrix12 = matrix12.astype(np.int32)
print(matrix12)

[ 10  20  30  40  50  60  70  80  90 100]


#### 3. Linear Algebra 

##### 3.1 Addition 

In [ ]:
#intuitively:
a = ([1,2,3,4,5])
b = ([5,4,3,2,1])
c = a+b
print(c)

#you'll have to use the numpy function to add two arrays.

d=np.add(a,b)
print(d)


[1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
[6 6 6 6 6]


##### 3.2 Subtraction

In [ ]:
#Now that you must have got an idea of how things work, I want you guys to try out subtraction 
#on your own. Subtract the above matrices a and b

e = np.subtract(a,b)
print(e)

[-4 -2  0  2  4]


##### 3.3 Multiplication

In [ ]:
#MULTIPLICATION

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.identity(3)

#Do it the conventional way and you'll realise this is not matrix multiplication. 
#It's just multiplying the arrays.

c = a*b
print(c)

#For this, we have to use a numpy function like this:
d = np.matmul(a,b)
print(d)

[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


##### 3.4 Division 


In [ ]:
a = np.array([2,4,6,8,10])
b = np.array([2,2,2,2,2])
c = np.divide(a,b)
print(c)

#I want the answer to be in int32
print(c.astype(np.int32))

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


##### 3.5 Determinant

In [ ]:
#I'm going to ask you guys a very simple question: What is the most fundamental difference between a 
#Matrix and a Determinant?
#Ans: Matrix is an arrangement of data, A Determinant is a single value 

#To calculate the determinant of a matrix, 
#first and foremost, obviously, the matrix needs to be a square matrix.
#this is the function we are going to use in order to find the determinant:
a = np.identity(3)
b = np.linalg.det(a)
print(b)

#since the determinant of an identity matrix is always 1, we have verified the working of this function.

1.0


##### 3.6 Trigonomety

In [ ]:
a = ([np.pi/2,np.pi/6])
print(a)

c = np.sin(a)
print(c)

#So we learnt two things in this:
#First, of course the fact that we can use trignonometric functions in this
#Second, how to use pi from the numpy library

[1.5707963267948966, 0.5235987755982988]
[1.  0.5]


#### 4. Statistics

In [ ]:
#In statistics, considering the scope of our lecture, we'll look at two functions:
#minimum and maximum

a = ([1,2,3,4,5,6,7,8,9])
#in the above array or a  matrix, it is easy to tell exactly which is the largest number in it
#however, in practical scnarios, we'll be dealing with arrays that are even 100x100
#regardless, we're going to find out which is the largest number among these
min_a = np.min(a)
print(min_a)
#similarly for max
max_a = np.max(a)
print(max_a)

1
9


## (VI) Matrix manipulation

#### 1. Reshaping 

In [ ]:
a= np.array([[1,2,3,4],[5,6,7,8]])
b= a.reshape((8,1)) #8rows and 1 column
print(b)

#From this, we come to know this function is goin to work as long as the total number of 
#elements in it remains the same.



[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


#### Exercise 6.1

In [ ]:
#Modify array a such that it becomes a 4x2, 2x2x2 array
c = a.reshape((4,2))
d = a.reshape((2,2,2))
print(c)
print("--------")
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### 2. Stacking 

In [ ]:
#Horizontal Stacking:
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])
c = np.vstack([a,b]) #stack and vstack both will do
c

#you may even stack them multiple times, according to the sequence you put in those brackets

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [ ]:
#Vertical Stacking:
a = np.array([[1,2],[3,4]])
b = np.full_like(a,2) #remember the full_like function from previous sections?
c = np.hstack([a,b])
c


array([[1, 2, 2, 2],
       [3, 4, 2, 2]])

## (VII) Miscellaneous

In [ ]:
#careful while copying arrays
#it works on pointers. 
#for example, you'd expect in this case that the changes made to b will not affect a 
a = np.array([[1,2],[3,4]])
b = a
a[1,1] = 99
print(b)
#However, they're actually both operating on the same array, beacuse a nad b are both 
#pointing to the same array.

#To avoid this, use:
c=a.copy()
print(c)

[[ 1  2]
 [ 3 99]]
[[ 1  2]
 [ 3 99]]


In [1]:
cars = ["Aston", "Audi", "McLaren "]
for i, x in enumerate(cars):
    print(x)

Aston
Audi
McLaren 
